version: 2

python:
  os: ubuntu-22.04
  version: 3.6
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true
  

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
