version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.6"
  jobs:
    pre_build:
    # Generate the Sphinx configuration for this Jupyter Book so it builds.
    - "jupyter-book config sphinx docs/"


python:
  install:
    - requirements: docs/requirements.txt
  # # version: "3.6"
  # install:
  #   - method: pip
  #     path: .
  #     extra_requirements:
  #       - docs
  # system_packages: true
  

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
