version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.6"

python:
  # version: "3.6"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true
  

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
