# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import sphinx_gallery
sys.path.insert(0, os.path.abspath('../'))
import sphinx_rtd_theme

import mprod


# -- Project information -----------------------------------------------------

project = 'mprod'
copyright = '2021, Elinav&Avron groups'
author = 'Uria Mor'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# extensions = [
#     'sphinx.ext.autodoc',
#     'sphinx.ext.viewcode',
#     'sphinx.ext.todo',
#     'sphinx.ext.autodoc',
#     'sphinx.ext.imgmath',
#     'sphinx.ext.napoleon'
# ]

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "numpydoc",
    'sphinx.ext.viewcode',
    # "sphinx.ext.linkcode",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinxcontrib.bibtex",
    # 'sphinx.ext.imgmath',
    # "sphinx.ext.imgconverter",
    # "sphinx_gallery.gen_gallery",
    "sphinx-prompt",
    'sphinx.ext.napoleon',
    "nbsphinx"
]


bibtex_bibfiles = ['refs.bib']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = [".rst", ".ipynb"]

# do not execute cells
# nbsphinx_execute = "always"
# nbsphinx_kernel_name = 'Python 3'
# nbsphinx_execute = "never"


# allow errors because not all tutorials build
nbsphinx_allow_errors = True

# napoleon related

napoleon_google_docstring = False
napoleon_use_param = False
napoleon_use_ivar = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# generate autosummary even if no references
autosummary_generate = True

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build',
                    'Thumbs.db',
                    '.DS_Store',
                    'trashed_docs',
                    '.ipynb_checkpoints',
                    "examples/.ipynb_checkpoints"]

autodoc_default_options = {"members": True, "inherited-members": False, "methods":True}

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
html_theme = 'sphinx_rtd_theme'
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
# html_theme_options = {"logo_only": True}
# html_logo = "_static/img/mprod_logo_small.png"
# html_favicon = "_static/img/mprod_logo_fav.png"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

