channels:
- conda-forge
dependencies:
- pip=21.0.1
- python=3.6
- numpy = 1.19.2
- scikit-learn = 0.24.1
- scipy = 1.5.3
- dataclasses = 0.7
- pandas = 1.1.5
- sphinx-gallery=0.9.0
- numpydoc=1.1.0
- sphinxcontrib-bibtex=2.3.0
- sphinx-prompt=1.4.0
- nbsphinx=0.8.6
- ipykernel=5.4.3
- seaborn=0.11.1
- jupyter=1.0.0
- sphinx-gallery = 0.9.0
- numpydoc = 1.1.0
- sphinxcontrib-bibtex = 2.3.0
- sphinx-prompt = 1.4.0
- nbsphinx = 0.8.6
- sphinx_rtd_theme = 0.5.2
- ipykernel = 5.4.3
- pip:
  - mprod-package==0.0.1a1

