name: Tests 

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6.8, 3.7, 3.8, 3.9]
        os: [macos-latest, ubuntu-20.04]
    
    steps:
      - uses: actions/checkout@v2
      - name: Build using Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # - name: pip install dependencies [pip]
      #   if: ${{ matrix.python-version >= 3.7 }} 
      #   run: |
      #     python -m pip install pip --upgrade pip
      #     pip install pytest
      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      #     pip install -e .

      - name: pip install dependencies [pip]
        # if: ${{ matrix.python-version < 3.7 }} 
        run: |
          python -m pip install pip --upgrade pip;
          pip install pytest;
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ ${{ matrix.python-version }} == 3.6.8 ]; then pip install dataclasses>=0.7; fi
          pip install -e .

      - name: unit tests [pytest]
        run: |
          pytest --show-capture=no -v --disable-warnings --junitxml=pytest.xml
